included:
  - OpenMarket # 프로젝트 이름
excluded: # 린트 과정에서 무시할 파일 경로. `included`보다 우선순위 높음
  - OpenMarket/AppDelegate.swift
  - OpenMarket/SceneDelegate.swift
identifier_name:
  min_length: # only min_length
    error: 4 # only error
disabled_rules: # 실행에서 제외할 룰 식별자들
  - colon
  - comma
  - control_statement
