# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'OpenMarket' do
  pod 'SwiftLint', '0.50'

  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!


  # Pods for OpenMarket

  target 'OpenMarketTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
